<template>
  <v-app>
    <v-container>
      <v-row>
        <v-col>
          <v-card>
            <p>ddwa</p>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </v-app>
</template>